# Generated by Django 5.2.5 on 2025-08-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_news_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
