# Generated by Django 5.2.5 on 2025-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_food_nomad_tourpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='video',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourpackage_images/'),
        ),
    ]
